---
title: "MB Assessed Practical 2"
author: "Richard Gotts"
date: "16/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.
```{r}
R0 <- function(beta, gamma, N)
{
  return(beta*N/gamma)
}
```

2.
```{r}
brr <- c()
gamma <- seq(0.1, 2, 0.01)
for(i in 1:191)
{
  brr <- c(brr, R0(0.01,gamma[i],100))
}
plot(gamma, brr, xlab="Recovery rate, gamma", ylab="Basic reproductive ratio, R0", type="l")
abline(h=1, col="red", lty=2)
```

3.
```{r}
SIR_dydt <- function(t, y, parms)
{
  beta <- parms[1]
  gamma <- parms[2]
  S <- y[1]
  I <- y[2]
  dS <- -1*beta*S*I
  dI <- beta*S*I - gamma*I
  return(list(c(dS,dI)))
}
```

4.
```{r}
S_test <- seq(10, 100, 10)
dI_test <- c()
for(i in 1:10)
{
  dS_dI <- unlist(SIR_dydt(t, c(S_test[i], 1), c(0.01, 0.4)))
  dI_test <- c(dI_test, dS_dI[2])
}
print(data.frame(S_test, dI_test))
```
With beta = 0.01, gamma = 0.4, and I = 1, dI/dt > 0 when S > 40, as shown in the output above. Therefore, the critical density of individuals required for an epidemic with these parameters is 40. Values of S > 40 satisfy the inequality beta*S > gamma; the reproductive ratio > 1.

5.
```{r}
library(deSolve)
beta <- 0.01
gamma <- 0.4
S_0 <- 99.9
I_0 <- 0.1
steps <- seq(0, 50, 0.1)
SIR_solution <- ode(c(S_0, I_0), steps, SIR_dydt, c(beta, gamma))
plot(SIR_solution[,2], SIR_solution[,3], type="l", xlab="S", ylab="I")
points(SIR_solution[1,2], SIR_solution[1,3], col="red", pch=1)
legend("topright", "Initial conditions", col="red", pch=1)
```

6.
```{r}
R <- c()
for(i in 1:501)
{
  R_t <- 100 - (SIR_solution[i,2] + SIR_solution[i,3])
  R <- c(R, R_t)
}
plot(SIR_solution[,1], SIR_solution[,2], type="l", col="blue", xlab="Time", ylab="Population density")
points(SIR_solution[,1], SIR_solution[,3], type="l", col="red")
points(SIR_solution[,1], R, type="l", col="green")
abline(h=100, lty=2, col="black")
legend(40, 75, c("N", "S", "I", "R"), col=c("black", "blue", "red", "green"), lty=c(2,1,1,1))
```

7.
```{r}
fes_eq <- function(f, r0)
{
  return(1 - f - exp(-1*r0*f))
}

r0 <- 2.5
f <- seq(0, 1, 0.001)
LHS <- c()
for(i in 1:1001)
{
  LHS <- c(LHS, fes_eq(f[i], r0))
}
plot(f, LHS, type="l", xlab="f", ylab="1 - f - exp(-r0*f)")

r0 <- 2.5
f <- 1.001
LHS <- fes_eq(f, r0)
while(LHS < 0)
{
  f <- f - 0.001
  LHS <- fes_eq(f, r0)
}
print(f)

fes_sol <- function(r0)
{
  f <- 1.001
  LHS <- fes_eq(f, r0)
  while(LHS < 0)
  {
    f <- f - 0.001
    LHS <- fes_eq(f, r0)
  }
  return(f)
}

r0 <- seq(1, 6, 0.01)
fes_r0 <- c()
for(i in 1:501)
{
  fes_r0 <- c(fes_r0, fes_sol(r0[i]))
}
plot(r0, fes_r0, type="l", xlab="Basic reproductive ratio, R0", ylab="Final epidemic size, f")
```

